language: python
sudo: false
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install pytest pytest-capturelog memory_profiler psutil
- pip install -e .
script:
- py.test --durations=20
